name: "Congressional Floor Actions"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main

permissions:
  contents: write
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   successfully:
#     description: "Feedback message of success"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: create-floor-actions-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "floor-actions.json"
          json: '{"title": "my json"}'
      - name: Commit File
        run: |
          git config --global user.email "mettacode@gmail.com"
          git config --global user.name "mettacode"
          git add -A floor-actions.json && git status
          git commit -am "Deployed floor-actions.json file"
          git push

# runs:
#   using: "node16"
#   main: "index.js"
