name: "Congressional Floor Actions"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/15 * * * 1-5"

permissions:
  contents: write

jobs:
  save_json_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node --version
      - name: run-javascript
        run: npm run data
      # - name: create-floor-actions-json
      #   uses: jsdaniell/create-json@v1.2.1
      #   with:
      #     name: "floor-actions.json"
      #     json: '{"title": "my json"}'
      - name: commit-floor-actions-json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Floor Action JSON Updated
