name: "Congressional Floor Actions"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: create-floor-actions-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "floor-actions.json"
          json: '{"title": "my json"}'
      - name: Save file to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Floor Action JSON Updated
      # - name: Commit File
      # run: |
      #   git config --global user.email "mettacode@gmail.com"
      #   git config --global user.name "mettacode"
      #   git add -A floor-actions.json && git status
      #   git commit -am "Deployed floor-actions.json file"
      #   git push
# runs:
#   using: "node16"
#   main: "index.js"
