name: "Congressional Floor Actions"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # create_floor_action_json:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: run-javascript
  #       uses: ./
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - run: node --version
  #     - run: npm run start
  save_json_file:
    runs-on: ubuntu-latest
    # needs: create_floor_action_json
    steps:
      - uses: actions/checkout@v2
      - run: node --version
      - name: run-javascript
        # uses: ./
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        run: npm run start
      - name: create-floor-actions-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "floor-actions.json"
          json: '{"title": "my json"}'
      - name: commit-floor-actions-json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Floor Action JSON Updated

  # commit_json_file:
  #   needs: create_json_file
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: commit-floor-actions-json
  #       uses: stefanzweifel/git-auto-commit-action@v4
  #       with:
  #         commit_message: Floor Action JSON Updated
  # - name: Commit File
  # run: |
  #   git config --global user.email "mettacode@gmail.com"
  #   git config --global user.name "mettacode"
  #   git add -A floor-actions.json && git status
  #   git commit -am "Deployed floor-actions.json file"
  #   git push
# runs:
#   using: "node16"
#   main: "index.js"
